service: serverless-crud

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'local'}
  region: sa-east-1
  memorySize: 128

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
